### ISSUE TITLE
Error: Cannot find module '@next/bundle-analyzer'

### ISSUE THREAD

**Issue by Kixunil** [apotdevin/thunderhub#104]
**Describe the problem/bug**
I'm attempting to package thunderhub as a Debian package. When I attempt to run it I get this error:

```
{ Error: Cannot find module '@next/bundle-analyzer'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/lib/thunderhub/next.config.js:2:28)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3) code: 'MODULE_NOT_FOUND' }
```

**Your environment**
* Version of ThunderHub: 0.8.13
* Deployment method: Debian package explained below
* Other relevant environment details: Debian Buster

**To Reproduce**
0. Use Debian 10
1. Clone the repository
2. Install npm using `apt install npm`
3. run `npm install --production`
4. copy the directory into `/usr/lib/thunderhub` of a different machine **without** npm
5. `cd /usr/lib/thunderhub`
6. `./node_modules/next/dist/bin/next start -- -p "$BIND_PORT"`

**Expected behavior**
ThunderHub starts

**Actual behavior**
ThunderHub crashes with the message above.

**Comment by apotdevin** [comment]
Ah yes, I should move `@next/bundle-analyzer` to be a production dependency.

Have you seen the dockerfiles for ARM archs? There you can see some dependencies that I have to install additional to the production ones:

`RUN npm install -D cross-env typescript @types/react @next/bundle-analyzer`

I need to look into this, some can maybe be excluded and the bundle-analyzer moved

**Comment by Kixunil** [comment]
Thanks! Will try to remove `--production` for now.
