### ISSUE TITLE
UnexpectedCloseChannelError: unable to gracefully close channel while peer is offline

### ISSUE THREAD

**Issue by Kixunil** [apotdevin/thunderhub#110]
**Describe the problem/bug**
A friend reported problems accessing ThunderHub and I found this in the log:

```
2020-07-31 11:08:43 error [THUB]: Error closing channel: [ 503,
  'UnexpectedCloseChannelError',
  { err:
     { Error: 2 UNKNOWN: unable to gracefully close channel while peer is offline (try force closing it instead): channel link not found
         at Object.exports.createStatusError (/usr/lib/thunderhub/node_modules/grpc/src/common.js:91:15)
         at ClientReadableStream._emitStatusIfDone (/usr/lib/thunderhub/node_modules/grpc/src/client.js:233:26)
         at ClientReadableStream._receiveStatus (/usr/lib/thunderhub/node_modules/grpc/src/client.js:211:8)
         at Object.onReceiveStatus (/usr/lib/thunderhub/node_modules/grpc/src/client_interceptors.js:1277:15)
         at InterceptingListener._callNext (/usr/lib/thunderhub/node_modules/grpc/src/client_interceptors.js:568:42)
         at InterceptingListener.onReceiveStatus (/usr/lib/thunderhub/node_modules/grpc/src/client_interceptors.js:618:8)
         at /usr/lib/thunderhub/node_modules/grpc/src/client_interceptors.js:1033:24
       [stack]:
        'Error: 2 UNKNOWN: unable to gracefully close channel while peer is offline (try force closing it instead): channel link not found\n    at Object.exports.crea
       [message]:
        '2 UNKNOWN: unable to gracefully close channel while peer is offline (try force closing it instead): channel link not found',
       code: 2,
       metadata: Metadata { _internal_repr: {}, flags: 0 },
       details:
        'unable to gracefully close channel while peer is offline (try force closing it instead): channel link not found' } },
```

**Your environment**
* Version of ThunderHub: 0.8.13
* Deployment method: Debian package
* Other relevant environment details: N/A

**To Reproduce**
Not sure, but the message suggests these steps should reproduce the behavior:
1. Create a network with two nodes and one channel
2. Bring down one node
3. Open ThunderHub

**Expected behavior**
A clear, user-friendly message about the peer being offline

**Actual behavior**
Stack trace in logs

**Comment by apotdevin** [comment]
So when logging in this channel error log appears?

**Comment by Kixunil** [comment]
Not sure because it worked fine later, when I got his message. I suppose he attempted to close the channels, that error caused it to fail and broke the app.

**Comment by apotdevin** [comment]
Will play around see if I can reproduce it 👍
