### ISSUE TITLE
Sub-satoshi Base Fees Cause UpdateFees operation to fail

### ISSUE THREAD

**Issue by initfortherekt** [apotdevin/thunderhub#136]
POST Data

```
Request POST data: 

{"operationName":"UpdateFees","variables":{"transaction_id":"XXXXXXX","transaction_vout":1,"base_fee_tokens"
:0.1,"fee_rate":10,"cltv_delta":40,"max_htlc_mtokens":"4959900000","min_htlc_mtokens":"1000","auth":{"type":"server","id":"XXX"}},"que
ry":"mutation UpdateFees($auth: authType!, $transaction_id: String, $transaction_vout: Int, $base_fee_tokens: F
loat, $fee_rate: Int, $cltv_delta: Int, $max_htlc_mtokens: String, $min_htlc_mtokens: String) {\n  updateFees(a
uth: $auth, transaction_id: $transaction_id, transaction_vout: $transaction_vout, base_fee_tokens: $base_fee_to
kens, fee_rate: $fee_rate, cltv_delta: $cltv_delta, max_htlc_mtokens: $max_htlc_mtokens, min_htlc_mtokens: $min
_htlc_mtokens)\n}\n"}

Response:

{"errors":[{"message":"Error","locations":[{"line":2,"column":3}],"path":["updateFees"],"extensions":{"code":"I
NTERNAL_SERVER_ERROR"}}],"data":{"updateFees":null}}
```

**Comment by initfortherekt** [comment]
Stack Trace:

```
2020-09-02 13:33:19 error [THUB]: RangeError: The number 0.1 cannot be converted to a BigInt because it is not an integer
    at BigInt (<anonymous>)
    at tokensAsMtokens (/home/rich/thunderhub/node_modules/ln-service/lightning/update_routing_fees.js:12:36)
    at asyncAuto.baseFeeMillitokens (/home/rich/thunderhub/node_modules/ln-service/lightning/update_routing_fees.js:74:26)
    at runTask (/home/rich/thunderhub/node_modules/async/auto.js:227:13)
    at /home/rich/thunderhub/node_modules/async/auto.js:167:31
    at processQueue (/home/rich/thunderhub/node_modules/async/auto.js:177:13)
    at taskComplete (/home/rich/thunderhub/node_modules/async/auto.js:193:9)
    at /home/rich/thunderhub/node_modules/async/auto.js:220:17
    at /home/rich/thunderhub/node_modules/async/internal/onlyOnce.js:12:16
    at validate (/home/rich/thunderhub/node_modules/ln-service/lightning/update_routing_fees.js:61:16) {
  [stack]: 'RangeError: The number 0.1 cannot be converted to a BigInt because it is not an integer\n' +
    '    at BigInt (<anonymous>)\n' +
    '    at tokensAsMtokens (/home/rich/thunderhub/node_modules/ln-service/lightning/update_routing_fees.js:12:36)\n' +
    '    at asyncAuto.baseFeeMillitokens (/home/rich/thunderhub/node_modules/ln-service/lightning/update_routing_fees.js:74:26)\n' +
    '    at runTask (/home/rich/thunderhub/node_modules/async/auto.js:227:13)\n' +
    '    at /home/rich/thunderhub/node_modules/async/auto.js:167:31\n' +
    '    at processQueue (/home/rich/thunderhub/node_modules/async/auto.js:177:13)\n' +
    '    at taskComplete (/home/rich/thunderhub/node_modules/async/auto.js:193:9)\n' +
    '    at /home/rich/thunderhub/node_modules/async/auto.js:220:17\n' +
    '    at /home/rich/thunderhub/node_modules/async/internal/onlyOnce.js:12:16\n' +
    '    at validate (/home/rich/thunderhub/node_modules/ln-service/lightning/update_routing_fees.js:61:16)',
  [message]: 'The number 0.1 cannot be converted to a BigInt because it is not an integer'
```

**Comment by initfortherekt** [comment]
It appears that ThunderHub only supports base_fee_tokens from ln-service's gRPC wrapper, which is in whole satoshis. 

ln-service specifies two possible base_fee expressions:
```
    [base_fee_mtokens]: <Base Fee Millitokens Charged Number>
    [base_fee_tokens]: <Base Fee Tokens Charged Number>
```
I suggest that the server's updateFee.ts resolver and the graphql mutation spec (`update_routing_fees.js`)  be modified to support mtokens, since it allows for a greater amount of specificity. The front end udpate modal could still take whole satoshis, but could also support fractional values (0.5, 1.2, etc...) and convert it to mtokens (x1000) prior to making the RPC.

**Comment by apotdevin** [comment]
Closed by https://github.com/apotdevin/thunderhub/pull/137
