### ISSUE TITLE
Problems restoring channels after LND db corrupted

### ISSUE THREAD

**Issue by vanjaime** [apotdevin/thunderhub#142]
**Describe the problem/bug**
After my LND db crashed. I removed the LND volume from docker and generated new one from scratch.
I had a backup generated from ThunderHub which is a txt file starts like this:

`{"backup":"537exxx`

**Your environment**
Docker BTCPayServer 

* Version of ThunderHub:
0.9.8

* Deployment method: 
Docker via BTCPayServer script

* Other relevant environment details:

**To Reproduce**
When I try Tools > Backups **recover funds from channels** "Backup String 

Paste the content of the file I created before from ThunderHub

Get this error:

"UnexpectedErrWhenRestoringChannelFunds"

If I try **Verify Backup String**
paste the content of the file, get this error "InvalidBackup String"

**Expected behavior**
I was expecting to be able to recover the channels when using the backup generated from ThunderHub

**Actual behavior**
Error

**Screenshots/Links**
![image](https://user-images.githubusercontent.com/16761309/93526945-2b4fee00-f906-11ea-8e03-9e4ad4f9607a.png)

![image](https://user-images.githubusercontent.com/16761309/93527421-d82a6b00-f906-11ea-919b-b2eef77dc22e.png)

What is the right method to restore the channels using the file generated from Thunderhub?

**Comment by apotdevin** [comment]
Hi, this is the correct way. 

Which browser are you using?
Can you check you are not copying any extra space before or after this string? 
What do you get in the server logs when you do this?

To check the logs in docker do:
1. `docker container ls` to list all running containers
2. `docker logs --follow [ThunderHub container id you can see with the previous command]`

**Comment by apotdevin** [comment]
Ah wait, I know the reason why. The channel backup file is encrypted by LND using the key derived from your nodes wallet seed. This means you have to restore your channels on a new node you initialise with the same seed as your previous node that crashed.

How did you initialise this new node?

**Comment by vanjaime** [comment]
I followed the instructions as listed herehttps://github.com/lightningnetwork/lnd/blob/master/docs/recovery.mdFor recovering onchain funds.However, I never see this {    "recovery_mode": true,    "recovery_finished": true,    "progress": 1}I get this instead:{
    "recovery_mode": false,
    "recovery_finished": false,
    "progress": 0
}I only have available the seeds and channel backup generated from thunder hub. I was able to pull on chain funds outside of lnd using the seeds which means they are correct. But I still have some funds in channels I'd like to recover. Also, it'd be good to know the whole restoring process in catastrophic events like this.On Sep 18, 2020 12:59 AM, Anthony Potdevin <notifications@github.com> wrote:
Ah wait, I know the reason why. The channel backup file is encrypted by LND using the key derived from your nodes wallet seed. This means you have to restore your channels on a new node you initialise with the same seed as your previous node that crashed.
How did you initialise this new node?

**Comment by vanjaime** [comment]
``

> Hi, this is the correct way.
> 
> Which browser are you using?
> Can you check you are not copying any extra space before or after this string?
> What do you get in the server logs when you do this?
> 
> To check the logs in docker do:
> 
> 1. `docker container ls` to list all running containers
> 2. `docker logs --follow [ThunderHub container id you can see with the previous command]`

here the results from log:

`2020-09-18 13:08:34 error [THUB]: Error recovering funds from channels: [
  503,
  'UnexpectedErrWhenRestoringChannelFunds',
  {
    err: Error: 2 UNKNOWN: unable to unpack chan backup: chacha20poly1305: message authentication failed
        at Object.exports.createStatusError (/app/node_modules/grpc/src/common.js:91:15)
        at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1209:28)
        at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)
        at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)
        at callback (/app/node_modules/grpc/src/client_interceptors.js:847:24) {
      [stack]: 'Error: 2 UNKNOWN: unable to unpack chan backup: chacha20poly1305: message authentication failed\n' +
        '    at Object.exports.createStatusError (/app/node_modules/grpc/src/common.js:91:15)\n' +
        '    at Object.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:1209:28)\n' +
        '    at InterceptingListener._callNext (/app/node_modules/grpc/src/client_interceptors.js:568:42)\n' +
        '    at InterceptingListener.onReceiveStatus (/app/node_modules/grpc/src/client_interceptors.js:618:8)\n' +
        '    at callback (/app/node_modules/grpc/src/client_interceptors.js:847:24)',
      [message]: '2 UNKNOWN: unable to unpack chan backup: chacha20poly1305: message authentication failed',
      code: 2,
      metadata: Metadata { _internal_repr: {}, flags: 0 },
      details: 'unable to unpack chan backup: chacha20poly1305: message authentication failed'
    }
  },
  [length]: 3
]
`

**Comment by apotdevin** [comment]
Seems to be more an issue with LND. It should show that the recovery is finished as is shown in the link you provided:
```
{
    "recovery_mode": true,
    "recovery_finished": true,
    "progress": 1
}
```

Maybe try rescanning? Or doing the recovery again? Seems like there is some issue here since it also cant decrypt the backup  string with the seed it has. 

Would suggest writing to the guys from LL on their slack https://join.slack.com/t/lightningcommunity/shared_invite/zt-bpe1a687-1UzHhrG15Fs_DMRI1jhbpg
