### ISSUE TITLE
GetWalletInfoErr: Bandwidth Exhausted

### ISSUE THREAD

**Issue by SteliosRammos** [apotdevin/thunderhub#163]
**Describe the problem/bug**
A few seconds after launching Thunderbolt and connecting to an account, I get logged out and the terminal output a bandwidth exhausted error.

**Your environment**
* Version of ThunderHub: 0.10.2
* Deployment method: Manual installation with yarn on a RaspberryPi 4
* Other relevant environment details: accessing the interface from a different device

**To Reproduce**
1. Login
2. Wait a bit

**Additional context**
The error does not always occur predictably. I have been able to go to pretty much all the pages at least once. This is the exact output on the terminal after some seconds of idle time:

```
2020-11-17 00:21:07 error [THUB]: [
  503,
  'UnexpectedErrorWhenGettingChainBalance',
  {
    err: Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
        at Object.callErrorFromStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
        at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:334:141)
        at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:297:181)
        at /home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:129:78
        at processTicksAndRejections (internal/process/task_queues.js:79:11) {
      [stack]: 'Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)\n' +
        '    at Object.callErrorFromStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n' +
        '    at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:176:52)\n' +
        '    at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:334:141)\n' +
        '    at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:297:181)\n' +
        '    at /home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:129:78\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:79:11)',
      [message]: '13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)',
      code: 13,
      details: 'Received RST_STREAM with code 2 (Internal server error)',
      metadata: Metadata { internalRepr: Map {}, options: {} }
    }
  },
  [length]: 3
]
2020-11-17 00:21:07 error [THUB]: [
  503,
  'GetChainBalanceError',
  {
    err: Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
        at Object.callErrorFromStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
        at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:334:141)
        at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:297:181)
        at /home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:129:78
        at processTicksAndRejections (internal/process/task_queues.js:79:11) {
      [stack]: 'Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)\n' +
        '    at Object.callErrorFromStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n' +
        '    at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:176:52)\n' +
        '    at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:334:141)\n' +
        '    at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:297:181)\n' +
        '    at /home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:129:78\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:79:11)',
      [message]: '13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)',
      code: 13,
      details: 'Received RST_STREAM with code 2 (Internal server error)',
      metadata: Metadata { internalRepr: Map {}, options: {} }
    }
  },
  [length]: 3
]
2020-11-17 00:21:09 error [THUB]: [
  503,
  'GetWalletInfoErr',
  {
    err: Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted
        at Object.callErrorFromStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:176:52)
        at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:334:141)
        at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:297:181)
        at /home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:129:78
        at processTicksAndRejections (internal/process/task_queues.js:79:11) {
      [stack]: 'Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted\n' +
        '    at Object.callErrorFromStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n' +
        '    at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client.js:176:52)\n' +
        '    at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:334:141)\n' +
        '    at Object.onReceiveStatus (/home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:297:181)\n' +
        '    at /home/stelios/thunderhub/node_modules/@grpc/grpc-js/build/src/call-stream.js:129:78\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:79:11)',
      [message]: '8 RESOURCE_EXHAUSTED: Bandwidth exhausted',
      code: 8,
      details: 'Bandwidth exhausted',
      metadata: Metadata { internalRepr: Map {}, options: {} }
    }
  },
  [length]: 3
]
```

**Comment by apotdevin** [comment]
Hey, thanks for reporting! This is most likely a problem with the NodeJS version.

Which NodeJS version do you have? Ideally it should be 14.15

**Comment by SteliosRammos** [comment]
Thanks, I upgraded NodeJS and the issue seems gone!
