### ISSUE TITLE
Internal Server Error on v0.12.18

### ISSUE THREAD

**Issue by tehelsper** [apotdevin/thunderhub#270]
**Describe the problem/bug**
Thunderhub fails to load on verion 0.12.18

**Your environment**
It's running on myNode

**To Reproduce**
- Launch Thunderhub
- See interval server error

**Expected behavior**
I expected Thunderhub to load properly and see the login screen.

**Actual behavior**
I got an internal server error.

**Additional context**
Here is the log from Thunderhub. Version 0.12.17 worked fine and I downgraded and was able to access Thunderhub again.

It looks like it can't find the admin macaroon in the latest version for some reason. The quotes and path also looks unusual in the log.

```
Jun 05 15:17:35 myNode thunderhub[27409]:     at createApolloClient (/opt/mynode/thunderhub/.next/server/pages/_app.js:1453:11)
Jun 05 15:17:35 myNode thunderhub[27409]:     at createIsomorphLink (/opt/mynode/thunderhub/.next/server/pages/_app.js:1440:9)
Jun 05 15:17:35 myNode thunderhub[27409]:     at __webpack_require__ (/opt/mynode/thunderhub/.next/server/pages/_app.js:23:31)
Jun 05 15:17:35 myNode thunderhub[27409]:     at Module.fbJj (/opt/mynode/thunderhub/.next/server/pages/_app.js:5653:109)
Jun 05 15:17:35 myNode thunderhub[27409]:     at getAccounts (/opt/mynode/thunderhub/.next/server/pages/_app.js:2871:10)
Jun 05 15:17:35 myNode thunderhub[27409]:     at getAccountsFromYaml (/opt/mynode/thunderhub/.next/server/pages/_app.js:2960:35)
Jun 05 15:17:35 myNode thunderhub[27409]:     at Array.map ()
Jun 05 15:17:35 myNode thunderhub[27409]:     at accounts.map (/opt/mynode/thunderhub/.next/server/pages/_app.js:2960:59)
Jun 05 15:17:35 myNode thunderhub[27409]:     at getParsedAccount (/opt/mynode/thunderhub/.next/server/pages/_app.js:2874:27)
Jun 05 15:17:35 myNode thunderhub[27409]:     at resolveEnvVarsInAccount (/opt/mynode/thunderhub/.next/server/pages/_app.js:2680:27)
Jun 05 15:17:35 myNode thunderhub[27409]: TypeError: Object.fromEntries is not a function
Jun 05 15:17:35 myNode thunderhub[27409]:     at createApolloClient (/opt/mynode/thunderhub/.next/server/pages/_app.js:1453:11)
Jun 05 15:17:35 myNode thunderhub[27409]:     at createIsomorphLink (/opt/mynode/thunderhub/.next/server/pages/_app.js:1440:9)
Jun 05 15:17:35 myNode thunderhub[27409]:     at __webpack_require__ (/opt/mynode/thunderhub/.next/server/pages/_app.js:23:31)
Jun 05 15:17:35 myNode thunderhub[27409]:     at Module.fbJj (/opt/mynode/thunderhub/.next/server/pages/_app.js:5653:109)
Jun 05 15:17:35 myNode thunderhub[27409]:     at getAccounts (/opt/mynode/thunderhub/.next/server/pages/_app.js:2871:10)
Jun 05 15:17:35 myNode thunderhub[27409]:     at getAccountsFromYaml (/opt/mynode/thunderhub/.next/server/pages/_app.js:2960:35)
Jun 05 15:17:35 myNode thunderhub[27409]:     at Array.map ()
Jun 05 15:17:35 myNode thunderhub[27409]:     at accounts.map (/opt/mynode/thunderhub/.next/server/pages/_app.js:2960:59)
Jun 05 15:17:35 myNode thunderhub[27409]:     at getParsedAccount (/opt/mynode/thunderhub/.next/server/pages/_app.js:2874:27)
Jun 05 15:17:35 myNode thunderhub[27409]:     at resolveEnvVarsInAccount (/opt/mynode/thunderhub/.next/server/pages/_app.js:2680:27)
Jun 05 15:17:35 myNode thunderhub[27409]: TypeError: Object.fromEntries is not a function
Jun 05 15:17:35 myNode thunderhub[27409]: 2021-06-05 15:17:35 error [THUB]: No admin.macaroon file found at path: '/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/'/admin.macaroon
Jun 05 15:17:35 myNode thunderhub[27409]: 2021-06-05 15:17:35 error [THUB]: No admin.macaroon file found at path: '/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/'/admin.macaroon
Jun 05 15:17:35 myNode thunderhub[27409]: 2021-06-05 15:17:35 verbose [THUB]: Found cookie at path /opt/mynode/thunderhub/.cookie
Jun 05 15:15:46 myNode thunderhub[27409]: info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
Jun 05 15:15:45 myNode thunderhub[27409]: info  - Loaded env from /opt/mynode/thunderhub/.env
Jun 05 15:15:45 myNode thunderhub[27409]: info  - Loaded env from /opt/mynode/thunderhub/.env.local
Jun 05 15:15:45 myNode thunderhub[27409]: ready - started server on 0.0.0.0:3030, url: http://localhost:3030
Jun 05 15:15:44 myNode thunderhub[27409]: > next start "-p" "3030"
Jun 05 15:15:44 myNode thunderhub[27409]: > thunderhub@0.12.18 start /opt/mynode/thunderhub
Jun 05 15:15:43 myNode systemd[1]: Started Thunderhub.
Jun 05 15:15:43 myNode thunderhub[27383]:     "synced_to_chain": true,
Jun 05 15:15:42 myNode thunderhub[27383]: Checking if LND is synced...
Jun 05 15:15:42 myNode thunderhub[27382]: Not shutting down!
Jun 05 15:15:42 myNode thunderhub[27382]: Checking if device is shutting down...
Jun 05 15:15:42 myNode systemd[1]: Starting Thunderhub...
```

**Comment by tehelsper** [comment]
Still seeing issue in v0.12.20.

**Comment by tavoplusde** [comment]
I am having the same issue. Did you solve it?

**Comment by tehelsper** [comment]
Try upgrading to the latest myNode beta - it has a downgrade to get Thunderhub working. The upgrade only works if a specific version of node has been installed.

**Comment by tavoplusde** [comment]
Thanks

Gustavo da Silva
