### ISSUE TITLE
v0.14.1 fails with 400 errors on bootup fails to start

### ISSUE THREAD

**Issue by miketwenty1** [apotdevin/thunderhub#365]
**Describe the problem/bug**
When using v0.12.31 of thunderhub. It fails to start when trying to connect to a lnd node running v0.14.1-beta

```
2021-12-02 21:31:15 error [THUB]: [ 400, 'ExpectedAuthenticatedLndGrpcForGetInfoRequest', [length]: 2 ]
2021-12-02 21:31:15 error [THUB]: [
    400,
    "ExpectedAuthenticatedLndGrpcForGetInfoRequest"
]
2021-12-02 21:31:15 error [THUB]: [ 400, 'ExpectedLndToGetChannels', [length]: 2 ]
2021-12-02 21:31:15 error [THUB]: [
    400,
    "ExpectedLndToGetChannels"
]
2021-12-02 21:31:15 error [THUB]: [ 400, 'ExpectedLndForPendingChainBalance', [length]: 2 ]
2021-12-02 21:31:15 error [THUB]: [
    400,
    "ExpectedLndForPendingChainBalance"
]
2021-12-02 21:31:15 error [THUB]: [ 400, 'ExpectedLndForPendingChannelsRequest', [length]: 2 ]
2021-12-02 21:31:15 error [THUB]: [
    400,
    "ExpectedLndForPendingChannelsRequest"
]
2021-12-02 21:31:15 error [THUB]: [ 400, 'ExpectedAuthenticatedLndToRetrieveChainBalance', [length]: 2 ]
2021-12-02 21:31:15 error [THUB]: [
    400,
    "ExpectedAuthenticatedLndToRetrieveChainBalance"
]
2021-12-02 21:31:15 error [THUB]: [ 400, 'ExpectedLndForGetPaymentsRequest', [length]: 2 ]
2021-12-02 21:31:15 error [THUB]: [
    400,
    "ExpectedLndForGetPaymentsRequest"
]
2021-12-02 21:31:15 error [THUB]: [ 400, 'ExpectedLndToGetChannels', [length]: 2 ]
2021-12-02 21:31:15 error [THUB]: [
    400,
    "ExpectedLndToGetChannels"
]
2021-12-02 21:31:15 error [THUB]: [ 400, 'ExpectedLndToGetForwardingHistory', [length]: 2 ]
2021-12-02 21:31:15 error [THUB]: [
    400,
    "ExpectedLndToGetForwardingHistory"
]
2021-12-02 21:31:15 error [THUB]: [ 400, 'ExpectedLndForNetworkInfoRequest', [length]: 2 ]
2021-12-02 21:31:15 error [THUB]: [
    400,
    "ExpectedLndForNetworkInfoRequest"
]
```

**Comment by miketwenty1** [comment]
front end errors when giving a machine with 8gb of ram.
only 1-2 gb of ram was ever used. before it crashed to the login screen.


![alt text](https://github.com/miketwenty1/images/blob/master/Screen%20Shot%202021-12-02%20at%205.45.17%20PM.png?raw=true)

Addtional docker logs from errors.
```
> thunderhub@0.12.31 start /app
> next start

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
2021-12-02 21:45:13 info [THUB]: Server accounts that will be available: zlnd1
2021-12-02 21:45:14 info [THUB]: Server accounts that will be available: zlnd1
(node:18) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
(Use `node --trace-deprecation ...` to show where the warning was created)
Warning: For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'yarn add sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
2021-12-02 22:43:32 error [THUB]: [
  503,
  'UnexpectedPendingChannelsErr',
  {
    err: Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted
        at Object.callErrorFromStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
        at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
        at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
        at /app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call-stream.js:160:78
        at processTicksAndRejections (internal/process/task_queues.js:75:11) {
      [stack]: 'Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted\n' +
        '    at Object.callErrorFromStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n' +
        '    at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client.js:180:52)\n' +
        '    at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)\n' +
        '    at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)\n' +
        '    at /app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call-stream.js:160:78\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:75:11)',
      [message]: '8 RESOURCE_EXHAUSTED: Bandwidth exhausted',
      code: 8,
      details: 'Bandwidth exhausted',
      metadata: Metadata { internalRepr: Map(0) {}, options: {} }
    }
  },
  [length]: 3
]
2021-12-02 22:44:04 error [THUB]: Authentication failed from ip: 172.31.78.191 - Invalid Password!
2021-12-02 22:45:14 error [THUB]: [
  503,
  'GetChainBalanceError',
  {
    err: Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)
        at Object.callErrorFromStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
        at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
        at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
        at /app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call-stream.js:160:78
        at processTicksAndRejections (internal/process/task_queues.js:75:11) {
      [stack]: 'Error: 13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)\n' +
        '    at Object.callErrorFromStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n' +
        '    at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client.js:180:52)\n' +
        '    at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)\n' +
        '    at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)\n' +
        '    at /app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call-stream.js:160:78\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:75:11)',
      [message]: '13 INTERNAL: Received RST_STREAM with code 2 (Internal server error)',
      code: 13,
      details: 'Received RST_STREAM with code 2 (Internal server error)',
      metadata: Metadata { internalRepr: Map(0) {}, options: {} }
    }
  },
  [length]: 3
]
2021-12-02 22:45:20 error [THUB]: [
  503,
  'UnexpectedErrorWhenGettingChainBalance',
  {
    err: Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted
        at Object.callErrorFromStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
        at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client.js:180:52)
        at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)
        at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)
        at /app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call-stream.js:160:78
        at processTicksAndRejections (internal/process/task_queues.js:75:11) {
      [stack]: 'Error: 8 RESOURCE_EXHAUSTED: Bandwidth exhausted\n' +
        '    at Object.callErrorFromStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call.js:31:26)\n' +
        '    at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client.js:180:52)\n' +
        '    at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:336:141)\n' +
        '    at Object.onReceiveStatus (/app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:299:181)\n' +
        '    at /app/node_modules/lightning/node_modules/@grpc/grpc-js/build/src/call-stream.js:160:78\n' +
        '    at processTicksAndRejections (internal/process/task_queues.js:75:11)',
      [message]: '8 RESOURCE_EXHAUSTED: Bandwidth exhausted',
      code: 8,
      details: 'Bandwidth exhausted',
      metadata: Metadata { internalRepr: Map(0) {}, options: {} }
    }
  },
  [length]: 3
]
API response for /api/v1 exceeds 4MB. This will cause the request to fail in a future version. https://nextjs.org/docs/messages/api-routes-body-size-limit
```

**Comment by mrsieb** [comment]
I have exact  the same behavior
