### ISSUE TITLE
TypeError: getContext is not a function

### ISSUE THREAD

**Issue by Lexus123** [apotdevin/thunderhub#383]
**Describe the problem/bug**
I followed the installation guide for `yarn`. But when I run `yarn start` and go to the IP address of my Raspberry Pi (with corresponding port), I get a 500 "Internal Server Error" error.

**Your environment**
* Version of ThunderHub: v0.12.31.
* Deployment method: From source with yarn.
* Other relevant environment details: yarn v1.22.17.

My `.env.local` file:
```
ACCOUNT_CONFIG_PATH='/home/ubuntu/.thunderhub/config.yaml'
```

My config file:
```
masterPassword: thunderhub-$abc$xyz
accounts:
  - name: ubuntu
    serverUrl: 127.0.0.1:10009
    lndDir: /home/ubuntu/.lnd
```

My LND config:
```
[Application Options]
tlsextraip=192.168.1.6
externalip=192.168.1.6
tlsautorefresh=true
restlisten=0.0.0.0:8080
rpclisten=0.0.0.0:10009
listen=127.0.0.1:9735
maxpendingchannels=5
color=#blabla
alias=somealias

[Tor]
tor.active=true
tor.v3=true
tor.streamisolation=true

[Bitcoin]
bitcoin.active=true
bitcoin.mainnet=true
bitcoin.node=bitcoind

[bitcoind]
bitcoind.dir=~/.bitcoin
bitcoind.rpcuser=someuser
bitcoind.rpcpass=somepassword
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333
```

**To Reproduce**
1. Follow installation docs for yarn.

**Expected behavior**
Show login screen.

**Actual behavior**
HTTP 500 error.

```
Jan 19 18:12:05 ubuntu systemd[1]: Started Thunderhub.
Jan 19 18:12:06 ubuntu yarn[92938]: yarn run v1.22.17
Jan 19 18:12:06 ubuntu yarn[92938]: $ next start -p 4000
Jan 19 18:12:06 ubuntu yarn[92960]: ready - started server on 0.0.0.0:4000, url: http://localhost:4000
Jan 19 18:12:06 ubuntu yarn[92960]: info  - Loaded env from /home/ubuntu/thunderhub/.env.local
Jan 19 18:12:06 ubuntu yarn[92960]: info  - Loaded env from /home/ubuntu/thunderhub/.env

Jan 19 18:13:31 ubuntu yarn[92960]: TypeError: getContext is not a function
Jan 19 18:13:31 ubuntu yarn[92960]:     at createIsomorphLink (/home/ubuntu/thunderhub/.next/server/chunks/3645.js:61:16)
Jan 19 18:13:31 ubuntu yarn[92960]:     at createApolloClient (/home/ubuntu/thunderhub/.next/server/chunks/3645.js:70:11)
Jan 19 18:13:31 ubuntu yarn[92960]:     at initializeApollo (/home/ubuntu/thunderhub/.next/server/chunks/3645.js:83:114)
Jan 19 18:13:31 ubuntu yarn[92960]:     at getProps (/home/ubuntu/thunderhub/.next/server/chunks/9581.js:120:58)
Jan 19 18:13:31 ubuntu yarn[92960]:     at getServerSideProps (/home/ubuntu/thunderhub/.next/server/pages/index.js:62:80)
Jan 19 18:13:31 ubuntu yarn[92960]:     at Object.renderToHTML (/home/ubuntu/thunderhub/node_modules/next/dist/server/render.js:555:26)
Jan 19 18:13:31 ubuntu yarn[92960]:     at async doRender (/home/ubuntu/thunderhub/node_modules/next/dist/server/base-server.js:1406:38)
Jan 19 18:13:31 ubuntu yarn[92960]:     at async /home/ubuntu/thunderhub/node_modules/next/dist/server/base-server.js:1501:28
Jan 19 18:13:31 ubuntu yarn[92960]:     at async /home/ubuntu/thunderhub/node_modules/next/dist/server/response-cache.js:63:36
Jan 19 18:13:31 ubuntu yarn[92960]: TypeError: getContext is not a function
Jan 19 18:13:31 ubuntu yarn[92960]:     at createIsomorphLink (/home/ubuntu/thunderhub/.next/server/chunks/3645.js:61:16)
Jan 19 18:13:31 ubuntu yarn[92960]:     at createApolloClient (/home/ubuntu/thunderhub/.next/server/chunks/3645.js:70:11)
Jan 19 18:13:31 ubuntu yarn[92960]:     at initializeApollo (/home/ubuntu/thunderhub/.next/server/chunks/3645.js:83:114)
Jan 19 18:13:31 ubuntu yarn[92960]:     at /home/ubuntu/thunderhub/.next/server/chunks/3645.js:96:51
Jan 19 18:13:31 ubuntu yarn[92960]:     at Object.Ja [as useMemo] (/home/ubuntu/thunderhub/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:27:240)
Jan 19 18:13:31 ubuntu yarn[92960]:     at exports.useMemo (/home/ubuntu/thunderhub/node_modules/react/cjs/react.production.min.js:23:113)
Jan 19 18:13:31 ubuntu yarn[92960]:     at useApollo (/home/ubuntu/thunderhub/.next/server/chunks/3645.js:96:44)
Jan 19 18:13:31 ubuntu yarn[92960]:     at App (/home/ubuntu/thunderhub/.next/server/pages/_app.js:102:89)
Jan 19 18:13:31 ubuntu yarn[92960]:     at d (/home/ubuntu/thunderhub/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
Jan 19 18:13:31 ubuntu yarn[92960]:     at bb (/home/ubuntu/thunderhub/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
Jan 19 18:13:31 ubuntu yarn[92960]: TypeError: getContext is not a function
Jan 19 18:13:31 ubuntu yarn[92960]:     at createIsomorphLink (/home/ubuntu/thunderhub/.next/server/chunks/3645.js:61:16)
Jan 19 18:13:31 ubuntu yarn[92960]:     at createApolloClient (/home/ubuntu/thunderhub/.next/server/chunks/3645.js:70:11)
Jan 19 18:13:31 ubuntu yarn[92960]:     at initializeApollo (/home/ubuntu/thunderhub/.next/server/chunks/3645.js:83:114)
Jan 19 18:13:31 ubuntu yarn[92960]:     at getProps (/home/ubuntu/thunderhub/.next/server/chunks/9581.js:120:58)
Jan 19 18:13:31 ubuntu yarn[92960]:     at getServerSideProps (/home/ubuntu/thunderhub/.next/server/pages/login.js:534:39)
Jan 19 18:13:31 ubuntu yarn[92960]:     at Object.renderToHTML (/home/ubuntu/thunderhub/node_modules/next/dist/server/render.js:555:26)
Jan 19 18:13:31 ubuntu yarn[92960]:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Jan 19 18:13:31 ubuntu yarn[92960]:     at async doRender (/home/ubuntu/thunderhub/node_modules/next/dist/server/base-server.js:1406:38)
Jan 19 18:13:31 ubuntu yarn[92960]:     at async /home/ubuntu/thunderhub/node_modules/next/dist/server/base-server.js:1501:28
Jan 19 18:13:31 ubuntu yarn[92960]:     at async /home/ubuntu/thunderhub/node_modules/next/dist/server/response-cache.js:63:36
Jan 19 18:13:32 ubuntu yarn[92960]: 2022-01-19 18:13:32 info [THUB]: Server accounts that will be available: ubuntu
```

This error log is coming from a service started with systemctl, but same happens when manually started with yarn.

**Comment by apotdevin** [comment]
Hey! Are you pulling from the latest master branch? Can you try deleting node_modules folder and package lock file and installing with `yarn`/`npm install` again?

Also best to use npm as it's whats used in this repo

**Comment by Lexus123** [comment]
Hi!

I checked out v0.12.31 specifically, but I'll try it later today with master as well.

I deleted node_modules twice now, but without avail.

I'll also try it with NPM later today. I only used yarn so far.

**Comment by apotdevin** [comment]
Try deleting the `package-lock` file as well and then installing the modules. This might help as well :)

**Comment by Lexus123** [comment]
Fixed by deleting `yarn.lock` and `node_modules` while staying on tag `v0.12.31` and following NPM installation.

Thanks! Kinda weird yarn doesn't work though...?
