### ISSUE TITLE
login page not working with yaml file set up

### ISSUE THREAD

**Issue by imirkth** [apotdevin/thunderhub#400]
**Describe the problem/bug**
login page doesn't respond as anticipated but i still have access to all other pages

**Your environment**
* Version of ThunderHub: 13.6
* Deployment method: npm run update
* Other relevant environment details: on linux ubuntu 18.04
* npm version 8.4.1

**To Reproduce**
1. start npm run
2. access localhost:3000\login
3. type in correct pwd (if i input an incorrect pwd, it's telling me it's incorrect)

**Expected behavior**
I'm expected to see the homepage of my node.

**Actual behavior**
the page i access says : "You do not have permission to view this page."
however if i go on localhost:3000\dashboard i can see the page without issues.

**Screenshots/Links**
If applicable, add screenshots or links to help explain your problem.

**Additional context**
the error i get in the terminal is  :
Error: Cannot find module 'next/dist/shared/lib/to-base-64.js'
Require stack:
- /home/imirk/thunderhub/.next/server/pages/index.js
- /home/imirk/thunderhub/node_modules/next/dist/server/require.js
- /home/imirk/thunderhub/node_modules/next/dist/server/next-server.js
- /home/imirk/thunderhub/node_modules/next/dist/server/next.js
- /home/imirk/thunderhub/dist/modules/view/view.service.js
- /home/imirk/thunderhub/dist/modules/view/view.controller.js
- /home/imirk/thunderhub/dist/modules/view/view.module.js
- /home/imirk/thunderhub/dist/app.module.js
- /home/imirk/thunderhub/dist/main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.mod._resolveFilename (/home/imirk/thunderhub/node_modules/next/build/webpack/require-hook.ts:142:26)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.3018 (/home/imirk/thunderhub/.next/server/pages/index.js:4723:18)
    at __webpack_require__ (/home/imirk/thunderhub/.next/server/webpack-runtime.js:25:42)
    at Object.6113 (/home/imirk/thunderhub/.next/server/chunks/6577.js:21:17)
    at __webpack_require__ (/home/imirk/thunderhub/.next/server/webpack-runtime.js:25:42)
    at Object.6577 (/home/imirk/thunderhub/.next/server/chunks/6577.js:624:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/imirk/thunderhub/.next/server/pages/index.js',
    '/home/imirk/thunderhub/node_modules/next/dist/server/require.js',
    '/home/imirk/thunderhub/node_modules/next/dist/server/next-server.js',
    '/home/imirk/thunderhub/node_modules/next/dist/server/next.js',
    '/home/imirk/thunderhub/dist/modules/view/view.service.js',
    '/home/imirk/thunderhub/dist/modules/view/view.controller.js',
    '/home/imirk/thunderhub/dist/modules/view/view.module.js',
    '/home/imirk/thunderhub/dist/app.module.js',
    '/home/imirk/thunderhub/dist/main.js'
  ]
}

**Comment by imirkth** [comment]
re-installed the repo from scratch and it worked.
