### ISSUE TITLE
Thunderhub master branch doesn't boot for me currently.

### ISSUE THREAD

**Issue by 2Fast2BCn** [apotdevin/thunderhub#412]
**Describe the problem/bug**
`yarn start` fails

**Your environment**
master branch
from sources on ubuntu

**To Reproduce**
yarn start

**Screenshots/Links**
````
WARN^[[39m ^[[38;5;3m[DependenciesScanner] ^[[39m^[[33mIn the next major version, Nest will not allow classes annotated with @Injectable(), @Catch(), and @Controller() decorators to appear in the "imports" array of a module.
Please remove "ConfigService" (including forwarded occurrences, if any) from all of the "imports" arrays.

Scope [AppModule -> AuthenticationModule -> ThrottlerModule]
````

````

/home/user/thunderhub/node_modules/@nestjs/graphql/node_modules/@graphql-tools/utils/index.js:3367
    for (const source of sources) {
                         ^
TypeError: sources is not iterable
    at mergeDeep (/home/user/thunderhub/node_modules/@nestjs/graphql/node_modules/@graphql-tools/utils/index.js:3367:26)
    at Array.reduce (<anonymous>)
    at schemaTransforms (/home/user/thunderhub/node_modules/@nestjs/graphql/dist/schema/src/makeExecutableSchema.js:65:70)
    at /home/user/thunderhub/node_modules/@nestjs/graphql/dist/schema/src/makeExecutableSchema.js:108:65
    at Array.reduce (<anonymous>)
    at makeExecutableSchema (/home/user/thunderhub/node_modules/@nestjs/graphql/dist/schema/src/makeExecutableSchema.js:108:29)
    at GraphQLFactory.mergeWithSchema (/home/user/thunderhub/node_modules/@nestjs/graphql/dist/graphql.factory.js:30:72)
    at ApolloDriver.start (/home/user/thunderhub/node_modules/@nestjs/apollo/dist/drivers/apollo.driver.js:19:25)
    at GraphQLModule.onModuleInit (/home/user/thunderhub/node_modules/@nestjs/graphql/dist/graphql.module.js:103:9)
    at Object.callModuleInitHook (/home/user/thunderhub/node_modules/@nestjs/core/hooks/on-module-init.hook.js:51:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
````

**Comment by 2Fast2BCn** [comment]
UPDATE: I changed from yarn to npm and that works.
