### ISSUE TITLE
Error claiming Boltz reverse-swap in the UI

### ISSUE THREAD

**Issue by TrezorHannes** [apotdevin/thunderhub#436]
**Describe the problem/bug**
I've tried a reverse-swap first time, on my node with a compiled thunderhub, running the latest LND.

1) Initiated via thunderhub > swaps
2) now next morning, it's ready to claim.
3) when clicking the claim button, my th log reports it can't get the mempool fees, due to a socks error. Don't think this is an issue, but still throw it out here
4) when adding 1sat/vByte and claim, TH log throws a "digital envelope routine unsupported error" and the UI does nothing. Logfile below
_The swap is still pending in my channel with boltz_

Notable
With the backup jason file, I'm trying to see if I can push the claim via other tools. Am in touch with Boltz in parallel. Also, the reverse-swap refunds after 24hrs anyway. But thought logging the bug anyway to derive the issue.

**Your environment**
* Version of ThunderHub: 0.13.7
* Deployment method: npm install && npm run build and running via systemctl
* Other relevant environment details:
node --version v17.6.0
npm --version 8.5.1
lnd version 0.14.2-beta commit=v0.14.2-beta
compiled binary via
`make && make install tags="autopilotrpc chainrpc invoicesrpc routerrpc signrpc walletrpc watchtowerrpc wtclientrpc"

**Expected behavior**
When clicking claim, it should send the L-BTC, and Boltz sends back the onchain sats - fees

**Actual behavior**
In the UI, nothing happens on "Claim". In the backend log, the following logentries are shown

**Screenshots/Links**
```
Apr 08 08:24:35 debian-nuc npm[502352]:   error: FetchError: request to http://raspiblitz.local:4080/api/v1/fees/recommended failed, reason: Socks5 proxy rejected connection - Failure
Apr 08 08:24:35 debian-nuc npm[502352]:       at ClientRequest.<anonymous> (/home/web/thunderhub/node_modules/next/dist/compiled/node-fetch/index.js:1:64142)
Apr 08 08:24:35 debian-nuc npm[502352]:       at ClientRequest.emit (node:events:527:28)
Apr 08 08:24:35 debian-nuc npm[502352]:       at onerror (/home/web/thunderhub/node_modules/agent-base/src/index.ts:236:9)
Apr 08 08:24:35 debian-nuc npm[502352]:       at callbackError (/home/web/thunderhub/node_modules/agent-base/src/index.ts:258:5)
Apr 08 08:24:35 debian-nuc npm[502352]:       at runMicrotasks (<anonymous>)
Apr 08 08:24:35 debian-nuc npm[502352]:       at processTicksAndRejections (node:internal/process/task_queues:96:5) {
Apr 08 08:24:35 debian-nuc npm[502352]:     type: 'system',
Apr 08 08:24:35 debian-nuc npm[502352]:     errno: undefined,
Apr 08 08:24:35 debian-nuc npm[502352]:     code: undefined
Apr 08 08:24:35 debian-nuc npm[502352]:   },
Apr 08 08:24:35 debian-nuc npm[502352]:   level: 'error',
Apr 08 08:24:35 debian-nuc npm[502352]:   message: 'Error getting bitcoin fees',
Apr 08 08:24:35 debian-nuc npm[502352]:   timestamp: '2022-04-08T06:24:35.084Z'
Apr 08 08:24:35 debian-nuc npm[502352]: }
Apr 08 08:24:35 debian-nuc npm[502352]: {
Apr 08 08:24:35 debian-nuc npm[502352]:   context: 'ExceptionsHandler',
Apr 08 08:24:35 debian-nuc npm[502352]:   stack: [
Apr 08 08:24:35 debian-nuc npm[502352]:     'Error: Problem getting Bitcoin fees.\n' +
Apr 08 08:24:35 debian-nuc npm[502352]:       '    at BitcoinResolver.getBitcoinFees (/home/web/thunderhub/src/server/modules/api/bitcoin/bitcoin.resolver.ts:52:13)\n' +
Apr 08 08:24:35 debian-nuc npm[502352]:       '    at runMicrotasks (<anonymous>)\n' +
Apr 08 08:24:35 debian-nuc npm[502352]:       '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
Apr 08 08:24:35 debian-nuc npm[502352]:       '    at target (/home/web/thunderhub/node_modules/@nestjs/core/helpers/external-context-creator.js:77:28)\n' +
Apr 08 08:24:35 debian-nuc npm[502352]:       '    at Object.getBitcoinFees (/home/web/thunderhub/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)'
Apr 08 08:24:35 debian-nuc npm[502352]:   ],
Apr 08 08:24:35 debian-nuc npm[502352]:   level: 'error',
Apr 08 08:24:35 debian-nuc npm[502352]:   message: 'Problem getting Bitcoin fees.',
Apr 08 08:24:35 debian-nuc npm[502352]:   timestamp: '2022-04-08T06:24:35.085Z'
Apr 08 08:24:35 debian-nuc npm[502352]: }

Apr 08 08:29:56 debian-nuc npm[502352]:   context: 'ExceptionsHandler',
Apr 08 08:29:56 debian-nuc npm[502352]:   stack: [
Apr 08 08:29:56 debian-nuc npm[502352]:     'Error: error:0308010C:digital envelope routines::unsupported\n' +
Apr 08 08:29:56 debian-nuc npm[502352]:       '    at new Hash (node:internal/crypto/hash:67:19)\n' +
Apr 08 08:29:56 debian-nuc npm[502352]:       '    at createHash (node:crypto:135:10)\n' +
Apr 08 08:29:56 debian-nuc npm[502352]:       '    at ripemd160 (/home/web/thunderhub/node_modules/bitcoinjs-lib/src/crypto.js:11:12)\n' +
Apr 08 08:29:56 debian-nuc npm[502352]:       '    at Object.hash160 (/home/web/thunderhub/node_modules/bitcoinjs-lib/src/crypto.js:30:10)\n' +
Apr 08 08:29:56 debian-nuc npm[502352]:       '    at p2shOutput (/home/web/thunderhub/node_modules/boltz-core/lib/swap/Scripts.ts:63:12)\n' +
Apr 08 08:29:56 debian-nuc npm[502352]:       '    at detectSwap (/home/web/thunderhub/node_modules/boltz-core/lib/swap/SwapDetector.ts:17:15)\n' +
Apr 08 08:29:56 debian-nuc npm[502352]:       '    at BoltzResolver.claimBoltzTransaction (/home/web/thunderhub/src/server/modules/api/boltz/boltz.resolver.ts:147:28)\n' +
Apr 08 08:29:56 debian-nuc npm[502352]:       '    at /home/web/thunderhub/node_modules/@nestjs/core/helpers/external-context-creator.js:70:33\n' +
Apr 08 08:29:56 debian-nuc npm[502352]:       '    at runMicrotasks (<anonymous>)\n' +
Apr 08 08:29:56 debian-nuc npm[502352]:       '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
Apr 08 08:29:56 debian-nuc npm[502352]:   ],
Apr 08 08:29:56 debian-nuc npm[502352]:   level: 'error',
Apr 08 08:29:56 debian-nuc npm[502352]:   message: 'error:0308010C:digital envelope routines::unsupported',
Apr 08 08:29:56 debian-nuc npm[502352]:   timestamp: '2022-04-08T06:29:56.265Z'
Apr 08 08:29:56 debian-nuc npm[502352]: }
```

Let me know if you need anything else to dig in.
Thanks

**Comment by TrezorHannes** [comment]
Appendix, I have a theory. It might be again due to Node 17.

When doing the same with boltz-cli, I got the following error too, which was more transparent:
```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at createHash (node:crypto:135:10)
    at ripemd160 (/home/admin/boltz-backend/node_modules/bitcoinjs-lib/src/crypto.js:11:12)
    at Object.hash160 (/home/admin/boltz-backend/node_modules/bitcoinjs-lib/src/crypto.js:30:10)
    at p2shOutput (/home/admin/boltz-backend/node_modules/boltz-core/dist/lib/swap/Scripts.js:67:32)
    at detectSwap (/home/admin/boltz-backend/node_modules/boltz-core/dist/lib/swap/SwapDetector.js:15:34)
    at Object.handler (/home/admin/boltz-backend/dist/lib/cli/commands/Claim.js:29:52)
    at /home/admin/boltz-backend/node_modules/yargs/build/index.cjs:1:9052
    at j (/home/admin/boltz-backend/node_modules/yargs/build/index.cjs:1:4931)
    at M.applyMiddlewareAndGetResult (/home/admin/boltz-backend/node_modules/yargs/build/index.cjs:1:9021) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
So after `export NODE_OPTIONS=--openssl-legacy-provider`, the claim went through successfully.

**Comment by apotdevin** [comment]
Most likely it's the NodeJS version. Sure bet would be to use the one thats in the Dockerfiles which have been tested. Try out version `14.15`

**Comment by TrezorHannes** [comment]
Likely a mix of node-version and the missing NODE_OPTIONS=--openssl-legacy-provider tag.
Closing this off
