### ISSUE TITLE
Error: Could not find a production build

### ISSUE THREAD

**Issue by seth586** [apotdevin/thunderhub#447]
**Describe the problem/bug**
```
Error: Could not find a production build in the '/root/thunderhub/src/client/.next' directory. Try building your app with 'next build' before starting the production server. https://nextjs.org/docs/messages/production-start-no-build-id
    at NextNodeServer.getBuildId (/root/thunderhub/node_modules/next/server/next-server.ts:168:15)
    at new Server (/root/thunderhub/node_modules/next/server/base-server.ts:293:25)
    at new NextNodeServer (/root/thunderhub/node_modules/next/server/next-server.ts:98:5)
    at NextServer.createServer (/root/thunderhub/node_modules/next/server/next.ts:124:12)
    at /root/thunderhub/node_modules/next/server/next.ts:140:23
```

**Your environment**
* Version of ThunderHub: 0.13.10
* Deployment method: FreeBSD 12.3 manual install
* Other relevant environment details: `npm version`:
```
{
  thunderhub: '0.13.10',
  npm: '8.5.2',
  node: '17.0.1',
  v8: '9.5.172.21-node.12',
  uv: '1.42.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.2',
  modules: '102',
  nghttp2: '1.46.0',
  napi: '8',
  llhttp: '6.0.4',
  openssl: '1.1.1l-freebsd',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0'
}

```

**To Reproduce**
1. `npm start`

**Actual behavior**
`{"statusCode":500,"message":"Internal server error"}` in browser.
error in console.

**Comment by Stef2k16** [comment]
Did you build before starting?
That is, did you run `npm run build` before running `npm start`?
