### ISSUE TITLE
LNURL auth is throwing error

### ISSUE THREAD

**Issue by arunned** [apotdevin/thunderhub#477]
**Describe the problem/bug**
When I try to do LN URL auth for lnmarkets, it is throwing this error
{
  context: 'ExceptionsHandler',
  stack: [
    'Error: ExpectedLndWithSupportForDeriveSharedKey\n' +
      '    at /home/ubuntu/thunderhub-0.13.15/src/server/modules/node/lnd/lnd.helpers.ts:5:13\n' +
      '    at runMicrotasks (<anonymous>)\n' +
      '    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n' +
      '    at LnUrlService.lnAuthUrlGenerator (/home/anedun/thunderhub-0.13.15/src/server/modules/api/lnurl/lnurl.service.ts:44:20)\n' +
      '    at LnMarketsService.getLnMarketsAuth (/home/anedun/thunderhub-0.13.15/src/server/modules/api/lnmarkets/lnmarkets.service.ts:140:22)\n' +
      '    at LnMarketsResolver.lnMarketsLogin (/home/anedun/thunderhub-0.13.15/src/server/modules/api/lnmarkets/lnmarkets.resolver.ts:164:36)\n' +
      '    at target (/home/anedun/thunderhub-0.13.15/node_modules/@nestjs/core/helpers/external-context-creator.js:77:28)\n' +
      '    at Object.lnMarketsLogin (/home/anedun/thunderhub-0.13.15/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)'
  ],
  level: 'error',
  message: 'ExpectedLndWithSupportForDeriveSharedKey',
  timestamp: '2022-08-16T20:20:12.181Z'
}

**LND 0.14 **
* 0.13.15:
* source download: 
* Other relevant environment details: tried node  version 14 and 16

**To Reproduce**
1. Go to '.lnurl auth'
2. Click on 'paste knurl'
3. Scroll down to 'click button'

**Expected behavior**
Successful lnurl auth 

Any pointer or feedback is much appreciated.

**Comment by arunned** [comment]
Solved it. for benefit of others - I had to compile LND from source with  tags="signrpc" so that it uses signer.proto DeriveSharedKey. Took a long time to connect the dots...!
