### ISSUE TITLE
Permission denied when creating invoice

### ISSUE THREAD

**Issue by drunkenclam** [apotdevin/thunderhub#50]
It seems to be working fine for me at first, but when I try to create an invoice I get this (yes, it's setup with Admin Macaroon):

```
2020-05-25 15:49:45 error [THUB]: Error getting invoice: [
  503,
  'AddInvoiceError',
  {
    err: Error: 2 UNKNOWN: permission denied
        at Object.exports.createStatusError (/home/thunderhub/thunderhub/node_modules/grpc/src/common.js:91:15)
        at Object.onReceiveStatus (/home/thunderhub/thunderhub/node_modules/grpc/src/client_interceptors.js:1209:28)
        at InterceptingListener._callNext (/home/thunderhub/thunderhub/node_modules/grpc/src/client_interceptors.js:568:42)
        at InterceptingListener.onReceiveStatus (/home/thunderhub/thunderhub/node_modules/grpc/src/client_interceptors.js:618:8)
        at callback (/home/thunderhub/thunderhub/node_modules/grpc/src/client_interceptors.js:847:24) {
      [stack]: 'Error: 2 UNKNOWN: permission denied\n' +
        '    at Object.exports.createStatusError (/home/thunderhub/thunderhub/node_modules/grpc/src/common.js:91:15)\n' +
        '    at Object.onReceiveStatus (/home/thunderhub/thunderhub/node_modules/grpc/src/client_interceptors.js:1209:28)\n' +
        '    at InterceptingListener._callNext (/home/thunderhub/thunderhub/node_modules/grpc/src/client_interceptors.js:568:42)\n' +
        '    at InterceptingListener.onReceiveStatus (/home/thunderhub/thunderhub/node_modules/grpc/src/client_interceptors.js:618:8)\n' +
        '    at callback (/home/thunderhub/thunderhub/node_modules/grpc/src/client_interceptors.js:847:24)',
      [message]: '2 UNKNOWN: permission denied',
      code: 2,
      metadata: Metadata { _internal_repr: {}, flags: 0 },
      details: 'permission denied'
    }
  },
  [length]: 3
]

```

**Your environment**
* Version of ThunderHub: 0.6.5 on Raspiblitz
* Deployment method: Followed the guide https://gist.github.com/openoms/8ba963915c786ce01892f2c9fa2707bc

**Comment by apotdevin** [comment]
Hi, thanks for opening the issue. Is this an account added on the browser or from the server?

**Comment by drunkenclam** [comment]
I followed the this guide: https://gist.github.com/openoms/8ba963915c786ce01892f2c9fa2707bc

So the user was added in the browser (I copied macaroons and tls cert from the Raspiblitz into the browser)

**Comment by apotdevin** [comment]
Can you update to the latest version (0.6.8), I fixed some account permissions issues lately which could solve this

**Comment by drunkenclam** [comment]
Correct! Working now, thanks!
