### ISSUE TITLE
Login fails after update from 0.13.16 -> 0.13.18

### ISSUE THREAD

**Issue by ssurfertuga** [apotdevin/thunderhub#503]
After updating (npm run update) from 0.13.16 to 0.13.18 login fails with the following error:

Jan 04 21:47:58 satoshi npm[3704970]: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/ramosh/thunderhub/node_modules/d3-scale/src/index.js from /home/ramosh/thunderhub/node_modules/@visx/scale/lib/scales/band.js not supported.
Jan 04 21:47:58 satoshi npm[3704970]: Instead change the require of index.js in /home/ramosh/thunderhub/node_modules/@visx/scale/lib/scales/band.js to a dynamic import() which is available in all CommonJS modules.
Jan 04 21:47:58 satoshi npm[3704970]:     at Object.<anonymous> (/home/ramosh/thunderhub/node_modules/@visx/scale/lib/scales/band.js:6:16)
Jan 04 21:47:58 satoshi npm[3704970]:     at Object.<anonymous> (/home/ramosh/thunderhub/node_modules/@visx/scale/lib/index.js:28:36)
Jan 04 21:47:58 satoshi npm[3704970]:     at Object.<anonymous> (/home/ramosh/thunderhub/node_modules/@visx/axis/lib/axis/Axis.js:9:14)
Jan 04 21:47:58 satoshi npm[3704970]:     at Object.<anonymous> (/home/ramosh/thunderhub/node_modules/@visx/axis/lib/index.js:13:36)
Jan 04 21:47:58 satoshi npm[3704970]:     at 2032 (/home/ramosh/thunderhub/src/client/.next/server/pages/index.js:7325:18)
Jan 04 21:47:58 satoshi npm[3704970]:     at __webpack_require__ (/home/ramosh/thunderhub/src/client/.next/server/webpack-runtime.js:25:42)
Jan 04 21:47:58 satoshi npm[3704970]:     at /home/ramosh/thunderhub/src/client/.next/server/chunks/4667.js:270:68
Jan 04 21:47:58 satoshi npm[3704970]:     at __webpack_require__.a (/home/ramosh/thunderhub/src/client/.next/server/webpack-runtime.js:103:13)
Jan 04 21:47:58 satoshi npm[3704970]:     at 7638 (/home/ramosh/thunderhub/src/client/.next/server/chunks/4667.js:260:21)
Jan 04 21:47:58 satoshi npm[3704970]:     at __webpack_require__ (/home/ramosh/thunderhub/src/client/.next/server/webpack-runtime.js:25:42)
Jan 04 21:47:58 satoshi npm[3704970]:     at /home/ramosh/thunderhub/src/client/.next/server/pages/index.js:7070:94
Jan 04 21:47:58 satoshi npm[3704970]:     at __webpack_require__.a (/home/ramosh/thunderhub/src/client/.next/server/webpack-runtime.js:103:13)
Jan 04 21:47:58 satoshi npm[3704970]:     at 2303 (/home/ramosh/thunderhub/src/client/.next/server/pages/index.js:7064:21)
Jan 04 21:47:58 satoshi npm[3704970]:     at __webpack_require__ (/home/ramosh/thunderhub/src/client/.next/server/webpack-runtime.js:25:42)
Jan 04 21:47:58 satoshi npm[3704970]:     at /home/ramosh/thunderhub/src/client/.next/server/pages/index.js:25:109
Jan 04 21:47:58 satoshi npm[3704970]:     at __webpack_require__.a (/home/ramosh/thunderhub/src/client/.next/server/webpack-runtime.js:103:13)
Jan 04 21:47:58 satoshi npm[3704970]:     at 4796 (/home/ramosh/thunderhub/src/client/.next/server/pages/index.js:11:21)
Jan 04 21:47:58 satoshi npm[3704970]:     at __webpack_require__ (/home/ramosh/thunderhub/src/client/.next/server/webpack-runtime.js:25:42)
Jan 04 21:47:58 satoshi npm[3704970]:     at __webpack_exec__ (/home/ramosh/thunderhub/src/client/.next/server/pages/index.js:7650:39)
Jan 04 21:47:58 satoshi npm[3704970]:     at /home/ramosh/thunderhub/src/client/.next/server/pages/index.js:7651:202
Jan 04 21:47:58 satoshi npm[3704970]:     at __webpack_require__.X (/home/ramosh/thunderhub/src/client/.next/server/webpack-runtime.js:190:21)
Jan 04 21:47:58 satoshi npm[3704970]:     at /home/ramosh/thunderhub/src/client/.next/server/pages/index.js:7651:47
Jan 04 21:47:58 satoshi npm[3704970]:     at Object.<anonymous> (/home/ramosh/thunderhub/src/client/.next/server/pages/index.js:7654:3)
Jan 04 21:47:58 satoshi npm[3704970]:     at Object.requirePage (/home/ramosh/thunderhub/node_modules/next/dist/server/require.js:48:12)
Jan 04 21:47:58 satoshi npm[3704970]:     at Object.loadComponents (/home/ramosh/thunderhub/node_modules/next/dist/server/load-components.js:58:23)
Jan 04 21:47:58 satoshi npm[3704970]:     at NextNodeServer.findPageComponents (/home/ramosh/thunderhub/node_modules/next/dist/server/next-server.js:429:63)
Jan 04 21:47:58 satoshi npm[3704970]:     at NextNodeServer.renderToResponse (/home/ramosh/thunderhub/node_modules/next/dist/server/base-server.js:1058:43)
Jan 04 21:47:58 satoshi npm[3704970]:     at pipe.req.req (/home/ramosh/thunderhub/node_modules/next/dist/server/base-server.js:682:38)
Jan 04 21:47:58 satoshi npm[3704970]:     at NextNodeServer.pipe (/home/ramosh/thunderhub/node_modules/next/dist/server/base-server.js:623:31)
Jan 04 21:47:58 satoshi npm[3704970]:     at NextNodeServer.render (/home/ramosh/thunderhub/node_modules/next/dist/server/base-server.js:682:21)
Jan 04 21:47:58 satoshi npm[3704970]:     at NextNodeServer.render (/home/ramosh/thunderhub/node_modules/next/dist/server/next-server.js:487:22)
Jan 04 21:47:58 satoshi npm[3704970]:     at Object.fn (/home/ramosh/thunderhub/node_modules/next/dist/server/base-server.js:496:32)
Jan 04 21:47:58 satoshi npm[3704970]:     at Object.fn (/home/ramosh/thunderhub/node_modules/next/dist/server/router.js:145:55)
Jan 04 21:47:58 satoshi npm[3704970]:     at async Router.execute (/home/ramosh/thunderhub/node_modules/next/dist/server/router.js:228:32)
Jan 04 21:47:58 satoshi npm[3704970]:     at async NextNodeServer.run (/home/ramosh/thunderhub/node_modules/next/dist/server/base-server.js:600:29)
Jan 04 21:47:58 satoshi npm[3704970]:     at async NextNodeServer.handleRequest (/home/ramosh/thunderhub/node_modules/next/dist/server/base-server.js:307:20)
Jan 04 21:47:58 satoshi npm[3704970]:     at async ViewController.showHome (/home/ramosh/thunderhub/dist/modules/view/view.controller.js:25:9)
Jan 04 21:47:58 satoshi npm[3704970]:     at async /home/ramosh/thunderhub/node_modules/@nestjs/core/router/router-execution-context.js:46:28
Jan 04 21:47:58 satoshi npm[3704970]:     at async /home/ramosh/thunderhub/node_modules/@nestjs/core/router/router-proxy.js:9:17 {
Jan 04 21:47:58 satoshi npm[3704970]:   code: 'ERR_REQUIRE_ESM'
Jan 04 21:47:58 satoshi npm[3704970]: }

Running:
Ubuntu 20.04.5
Node 18.12.1
npm 9.2.0
LND 0.15.4-beta

Not sure if this is related to also upgrading NPM to 9.2.0 ??

**Comment by ssurfertuga** [comment]
Apparently not related to npm upgrade to 9.2.0. I just downgraded to the previous working version 8.19.2 and I still get the same error on logs.
Anyone else having this issue?
