### ISSUE TITLE
Received RST_STREAM

### ISSUE THREAD

**Issue by Dark345** [apotdevin/thunderhub#526]
hello
I'm getting this error on startup:

```
err: [
    503,
    'GetWalletInfoErr',
    {
      err: Error: 13 INTERNAL: Received RST_STREAM with code 2 triggered by internal client error: Protocol error
          at Object.callErrorFromStatus (/var/lswww/thunderhub/node_modules/lightning/node_modules/@grpc/grpc-js/src/call.ts:81:17)
          at Object.onReceiveStatus (/var/lswww/thunderhub/node_modules/lightning/node_modules/@grpc/grpc-js/src/client.ts:358:36)
          at Object.onReceiveStatus (/var/lswww/thunderhub/node_modules/lightning/node_modules/@grpc/grpc-js/src/client-interceptors.ts:462:34)
          at Object.onReceiveStatus (/var/lswww/thunderhub/node_modules/lightning/node_modules/@grpc/grpc-js/src/client-interceptors.ts:424:48)
          at /var/lswww/thunderhub/node_modules/lightning/node_modules/@grpc/grpc-js/src/call-stream.ts:334:24
          at processTicksAndRejections (node:internal/process/task_queues:78:11)
      for call at
          at ServiceClientImpl.makeUnaryRequest (/var/lswww/thunderhub/node_modules/lightning/node_modules/@grpc/grpc-js/src/client.ts:328:30)
          at ServiceClientImpl.<anonymous> (/var/lswww/thunderhub/node_modules/lightning/node_modules/@grpc/grpc-js/src/make-client.ts:189:15)
          at asyncAuto.getWalletInfo (/var/lswww/thunderhub/node_modules/lightning/lnd_methods/info/get_wallet_info.js:59:28)
          at runTask (/var/lswww/thunderhub/node_modules/async/auto.js:293:13)
          at /var/lswww/thunderhub/node_modules/async/auto.js:233:31
          at processQueue (/var/lswww/thunderhub/node_modules/async/auto.js:243:13)
          at taskComplete (/var/lswww/thunderhub/node_modules/async/auto.js:259:9)
          at /var/lswww/thunderhub/node_modules/async/auto.js:286:17
          at /var/lswww/thunderhub/node_modules/async/internal/onlyOnce.js:12:16
          at validate (/var/lswww/thunderhub/node_modules/lightning/lnd_methods/info/get_wallet_info.js:54:16) {
        code: 13,
        details: 'Received RST_STREAM with code 2 triggered by internal client error: Protocol error',
        metadata: Metadata { internalRepr: Map(0) {}, options: {} }
      }
    }
  ],
  level: 'error',
  message: 'Error connecting to node',
  timestamp: '2023-04-21T13:34:07.163Z'
```

.env.local content
```
LISTEN=0.0.0.0
PORT=3000

LOG_LEVEL='info'
DISABLE_TWOFA=true

THEME='dark'
CURRENCY='sat'


FETCH_PRICES=true
FETCH_FEES=true
DISABLE_LINKS=false
DISABLE_LNMARKETS=false
NO_VERSION_CHECK=false

ACCOUNT_CONFIG_PATH='/path/to/accounts.yaml'

```

accounts.yaml content
```
masterPassword: thunderhub-hashed
accounts:
  - name: mylnd
    serverUrl: mylnd:8080
    macaroonPath: /path/to/macaroon/admin.macaroon
    certificatePath: /path/to/thunderhub/tls.cert
    password: thunderhub-hashed

```
LND is on a remote machine, macaroon and tls cert imported into thunderhub machine

OS: Debian 11 amd64
Node: v16.20.0
npm: 8.19.4

already tried node v14 and v18, same error.

Any help is appreciated!

**Comment by Dark345** [comment]
Well it turned out that i was connecting to LND's REST port instead of gRPC port. Closing now
