### ISSUE TITLE
Error «ERR_REQUIRE_ESM»

### ISSUE THREAD

**Issue by n-e-t-d-i-v-e-r** [apotdevin/thunderhub#528]
**Describe the problem/bug**
Want install Thunderhub on my Raspibolt. But during the build it breaks with Error «ERR_REQUIRE_ESM».

**Your environment**
Thunderhub 0.13.18
* Deployment method: 
* Other relevant environment details: Tried to install it from this manual: https://raspibolt.org/guide/bonus/lightning/thunderhub.html

**To Reproduce**
Go thru the process and everything will work until step «npm run build»

**Expected behavior**
The build runs till the end without breaking by an error.

**Actual behavior**
`> Build error occurred
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/thunderhub/thunderhub/node_modules/d3-scale/src/index.js from /home/thunderhub/thunderhub/node_modules/@visx/scale/lib/scales/band.js not supported.
Instead change the require of index.js in /home/thunderhub/thunderhub/node_modules/@visx/scale/lib/scales/band.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/thunderhub/thunderhub/node_modules/@visx/scale/lib/scales/band.js:6:16)
    at Object.<anonymous> (/home/thunderhub/thunderhub/node_modules/@visx/scale/lib/index.js:28:36)
    at Object.<anonymous> (/home/thunderhub/thunderhub/node_modules/@visx/axis/lib/axis/Axis.js:9:14)
    at Object.<anonymous> (/home/thunderhub/thunderhub/node_modules/@visx/axis/lib/index.js:13:36)
    at Object.2032 (/home/thunderhub/thunderhub/src/client/.next/server/pages/transactions.js:1005:18)
    at __webpack_require__ (/home/thunderhub/thunderhub/src/client/.next/server/webpack-runtime.js:25:42)
    at /home/thunderhub/thunderhub/src/client/.next/server/chunks/4667.js:19:68
    at Function.__webpack_require__.a (/home/thunderhub/thunderhub/src/client/.next/server/webpack-runtime.js:103:13)
    at Object.8435 (/home/thunderhub/thunderhub/src/client/.next/server/chunks/4667.js:9:21)
    at __webpack_require__ (/home/thunderhub/thunderhub/src/client/.next/server/webpack-runtime.js:25:42)
    at /home/thunderhub/thunderhub/src/client/.next/server/pages/transactions.js:347:84
    at Function.__webpack_require__.a (/home/thunderhub/thunderhub/src/client/.next/server/webpack-runtime.js:103:13)
    at Object.6734 (/home/thunderhub/thunderhub/src/client/.next/server/pages/transactions.js:339:21)
    at __webpack_require__ (/home/thunderhub/thunderhub/src/client/.next/server/webpack-runtime.js:25:42)
    at /home/thunderhub/thunderhub/src/client/.next/server/pages/transactions.js:501:75
    at Function.__webpack_require__.a (/home/thunderhub/thunderhub/src/client/.next/server/webpack-runtime.js:103:13)
    at Object.794 (/home/thunderhub/thunderhub/src/client/.next/server/pages/transactions.js:488:21)
    at __webpack_require__ (/home/thunderhub/thunderhub/src/client/.next/server/webpack-runtime.js:25:42)
    at /home/thunderhub/thunderhub/src/client/.next/server/pages/transactions.js:38:87
    at Function.__webpack_require__.a (/home/thunderhub/thunderhub/src/client/.next/server/webpack-runtime.js:103:13)
    at Object.7089 (/home/thunderhub/thunderhub/src/client/.next/server/pages/transactions.js:11:21)
    at __webpack_require__ (/home/thunderhub/thunderhub/src/client/.next/server/webpack-runtime.js:25:42)
    at __webpack_exec__ (/home/thunderhub/thunderhub/src/client/.next/server/pages/transactions.js:1302:39)
    at /home/thunderhub/thunderhub/src/client/.next/server/pages/transactions.js:1303:172
    at Function.__webpack_require__.X (/home/thunderhub/thunderhub/src/client/.next/server/webpack-runtime.js:190:21)
    at /home/thunderhub/thunderhub/src/client/.next/server/pages/transactions.js:1303:47
    at Object.<anonymous> (/home/thunderhub/thunderhub/src/client/.next/server/pages/transactions.js:1306:3)
    at Object.requirePage (/home/thunderhub/thunderhub/node_modules/next/dist/server/require.js:48:12)
    at Object.loadComponents (/home/thunderhub/thunderhub/node_modules/next/dist/server/load-components.js:58:23)
    at /home/thunderhub/thunderhub/node_modules/next/dist/build/utils.js:591:52
    at Span.traceAsyncFn (/home/thunderhub/thunderhub/node_modules/next/dist/trace/trace.js:75:26)
    at Object.isPageStatic (/home/thunderhub/thunderhub/node_modules/next/dist/build/utils.js:587:29)
    at execFunction (/home/thunderhub/thunderhub/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2826)
    at execHelper (/home/thunderhub/thunderhub/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2484)
    at execMethod (/home/thunderhub/thunderhub/node_modules/next/dist/compiled/jest-worker/processChild.js:1:2572)
    at process.messageListener (/home/thunderhub/thunderhub/node_modules/next/dist/compiled/jest-worker/processChild.js:1:1282)
    at process.emit (node:events:513:28) {
  type: 'Error',
  code: 'ERR_REQUIRE_ESM'
}
`

**Additional context**
Seems like my node.js-version is not matching with the actuall version of thunderhub. Would be glad if someone can put me in here the solution ak commands to downgrade node.js to the needed version for installing thunderhub without issue.

**Comment by kenshortrede** [comment]
Same problem here. Tried to update the package, and now it's impossible to solve the issues. Tried node 20.2.0, 18.6.0, 16.16.0, 

14.15.1 --> This creates another broken dependency with react

**Comment by n-e-t-d-i-v-e-r** [comment]
@NickRHill does this mean I should uninstall npm and thunderbold and reinstall both without running «npm audit fix»?

**Comment by NickRHill** [comment]
You can rename your node_modules directory and packages.json then re-run. If all goes well, delete your renamed folders/ files

**Comment by zyklopisch** [comment]
I also have this error - is there a way to fix it?

**Comment by n-e-t-d-i-v-e-r** [comment]
> I confirm I have the same problem on Debian testing. npm install lists 8 moderate 16 high vulnerabilities and then suggests running npm audit fix If I run npm audit fix then npm run build it fails with Error [ERR_REQUIRE_ESM]: require() of ES Module /home/xxxx/build/thunderhub/node_modules/d3-scale/src/index.js from /home/xxxx/build/thunderhub/node_modules/@visx/scale/lib/scales/band.js not supported.
> 
> If I don't run npm audit fix the build appears to run to completion.

this was exactly the issue. to solve it, I uninstalled npm, thunderhub and json. then first installed npm, without running «npm audit fix» and after installing thunderhub new, it runs.

thx for support.
