### ISSUE TITLE
Thunderhub and auto backup to Amboss doesn't work

### ISSUE THREAD

**Issue by Perlover** [apotdevin/thunderhub#555]
**Describe the problem/bug**

I have an account on Amboss, also inside Thunderhub under BTCPay I set auto backup (screenshot: https://nostr.build/p/nb12245.png). I have an automatic backup of the SCB file. In manual mode (by pressing the "Push" button in Thunderhub) - backup works fine (screenshot, only manual backups are visible there: https://nostr.build/p/nb12244.png). But it doesn't work automatically.

**Your environment**

* BTCPay v1.10.3+983b8c1f5
* Version of ThunderHub: v0.13.19
* Deployment method: From BTCPay (Docker method from LunaNode provider from template)
* Other relevant environment details:

**To Reproduce**

In addition to Thunder hub backup, I have a bash script running that monitors changes to the scb file through the `inotifywait -e modify -e attrib $SCB_SOURCE_FILE` command. When I open a channel, the file changes twice (immediately after funding and the second time after the required number of confirmations to open the channel) and my script executes backup twice in the git repository. But according to the logs of the `generated_bitcoin_thub_1` docker container, nothing happens at this time (to see logs of example). Only JSON logs that the channel is started to open and that there is no longer one channel.

I believe that either the Thundersub monitoring script is not running, or there are some problems with it in crontab. Since backup works in manual mode, apparently Thunderhub has access to the file and rights.

I created a ticket on [BTCPay](https://github.com/btcpayserver/btcpayserver/issues/5153), but [they are sure that the problem is in your software](https://github.com/btcpayserver/btcpayserver/issues/5153#issuecomment-1634131137).

Even right now I decided to check again and went to Amboss. I have the last backup there from July 5. Inside my ThunderHub, an automatic backup option is enabled. Then I manually pressed Push button (Push Backup to Amboss) and after that backup successfully appeared in amboss with a much larger file size. From this I conclude that automatic tracking and sending of backup file do not work at any stage.

**Expected behavior**

If an automatic Backup is turned on (Thunderhub / Amboss / Backups / "By disabling automatic backups to Amboss, ThunderHub will no longer push encrypted backups" / We see the button like "Disable"), then it should work.

**Actual behavior**

To see above

**Screenshots/Links**

https://nostr.build/p/nb12245.png

https://nostr.build/p/nb12244.png

**Comment by mariodian** [comment]
I have a similar issue that may or may not be related. I can manually push the backup to amboss however, I can't even enable auto bakcups in thunderhub. 

I get the following error:
```
{
    "errors": [
        {
            "message": "Error enabling auto backups",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "toggleConfig"
            ],
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "stacktrace": [
                    "Error: Error enabling auto backups",
                    "    at UserConfigService.toggleValue (/home/ubuntu/source/Bitcoin/thunderhub/dist/modules/api/userConfig/userConfig.service.js:55:19)",
                    "    at UserConfigService.toggleAutoBackups (/home/ubuntu/source/Bitcoin/thunderhub/dist/modules/api/userConfig/userConfig.service.js:80:14)",
                    "    at UserConfigResolver.toggleConfig (/home/ubuntu/source/Bitcoin/thunderhub/dist/modules/api/userConfig/userConfig.resolver.js:139:40)",
                    "    at /home/ubuntu/source/Bitcoin/thunderhub/node_modules/@nestjs/core/helpers/external-context-creator.js:67:33",
                    "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
                    "    at async target (/home/ubuntu/source/Bitcoin/thunderhub/node_modules/@nestjs/core/helpers/external-context-creator.js:74:28)",
                    "    at async Object.toggleConfig (/home/ubuntu/source/Bitcoin/thunderhub/node_modules/@nestjs/core/helpers/external-proxy.js:9:24)"
                ]
            }
        }
    ],
    "data": null
}
```

Thunderhub 0.13.30
