### ISSUE TITLE
Thunderhub crashes after login

### ISSUE THREAD

**Issue by Wired4ncer** [apotdevin/thunderhub#565]
With newest version, Thunderhub doesn't load when I input password in. It reloads back to login page. Log does show error.

**5.15.0-82-generic #91-Ubuntu SMP Mon Aug 14 14:14:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux**
* Version of ThunderHub: 0.13.21
* Deployment method - manual install via npm using minibolt guide https://v2.minibolt.info/lightning/lightning/web-app

**Expected behavior**
Login and open Thub web interface.

**Actual behavior**
Page reloads back to login window.

**Log details**:
```
Started Thunderhub.
: (node:1318006) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored in a future version.
: (Use `node --trace-deprecation ...` to show where the warning was created)
: upstream image response failed for /assets/amboss_icon.png TypeError: fetch failed
:     at Object.fetch (/home/thunderhub/thunderhub/node_modules/next/dist/compiled/undici/index.js:1:26669)
:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
:     at async invokeRequest (/home/thunderhub/thunderhub/node_modules/next/dist/server/lib/server-ipc/invoke-request.js:17:12)
:     at async /home/thunderhub/thunderhub/node_modules/next/dist/server/next-server.js:359:35
:     at async imageOptimizer (/home/thunderhub/thunderhub/node_modules/next/dist/server/image-optimizer.js:537:13)
:     at async cacheEntry.imageResponseCache.get.incrementalCache (/home/thunderhub/thunderhub/node_modules/next/dist/server/next-server.js:598:60)
:     at async /home/thunderhub/thunderhub/node_modules/next/dist/server/response-cache/index.js:99:36 {
:   cause: Error: connect ECONNREFUSED 127.0.0.1:3000
:       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16) {
:     errno: -111,
:     code: 'ECONNREFUSED',
:     syscall: 'connect',
:     address: '127.0.0.1',
:     port: 3000
:   }
: }
: ImageError: "url" parameter is valid but upstream response is invalid
:     at imageOptimizer (/home/thunderhub/thunderhub/node_modules/next/dist/server/image-optimizer.js:549:19)
:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
:     at async cacheEntry.imageResponseCache.get.incrementalCache (/home/thunderhub/thunderhub/node_modules/next/dist/server/next-server.js:598:60)
:     at async /home/thunderhub/thunderhub/node_modules/next/dist/server/response-cache/index.js:99:36 {
:   statusCode: 500
: }
```

**Comment by MButcho** [comment]
I have the same issue regarding "upstream image response failed for /assets/amboss_icon.png TypeError: fetch failed". As far as I can see, this issue in my environment is caused by ThunderHub connecting to a wrong port. I have different port defined in .env, however it is trying to fetch from 3000: "[upstream image response failed for /assets/amboss_icon.png TypeError: fetch failed](cause: Error: connect ECONNREFUSED 127.0.0.1:3000)"

**Comment by Wired4ncer** [comment]
This error is happening for me again in the newest version 0.13.29 
Was there any reason it started to happen again?
Anyone found solution?
