### ISSUE TITLE
Update to 0.13.23 and it won't start

### ISSUE THREAD

**Issue by pulkitsharma** [apotdevin/thunderhub#573]
**Describe the problem/bug**
Updating to latest version failed with the following error.

**Your environment**
* Version of ThunderHub: 0.13.23
* Deployment method: npm run update
* Other relevant environment details: ubuntu. running smoothly since last 4-5 months.

**To Reproduce**
Execute the command : npm run update
Also tried sh ./scripts/updateToLatest.sh

**Logs**
SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/pulkitsharma/thunderhub/node_modules/next/dist/telemetry/post-payload.js:17:20)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! thunderhub@0.13.23 build:next: `cd src/client && next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the thunderhub@0.13.23 build:next script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pulkitsharma/.npm/_logs/2023-10-21T14_32_51_573Z-debug.log

Also tried running : npm run start:prod:env

> thunderhub@0.13.23 start:prod:env /home/pulkitsharma/thunderhub
> NODE_ENV=production node dist/main

/home/pulkitsharma/thunderhub/node_modules/@nestjs/common/file-stream/streamable-file.js:31
            this.options.length ??= bufferOrReadStream.length;
                                ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/home/pulkitsharma/thunderhub/node_modules/@nestjs/common/file-stream/index.js:4:22)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! thunderhub@0.13.23 start:prod:env: `NODE_ENV=production node dist/main`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the thunderhub@0.13.23 start:prod:env script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pulkitsharma/.npm/_logs/2023-10-21T14_55_01_400Z-debug.log

**Comment by pulkitsharma** [comment]
Updated node to latest version v21. Getting new error now.
Logs - 
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting and checking validity of types    
 ✓ Creating an optimized production build    
 ✓ Compiled successfully
   Collecting page data  ...ReferenceError: window is not defined
    at /home/pulkitsharma/thunderhub/src/client/.next/server/chunks/1010.js:14:70826
    at 75015 (/home/pulkitsharma/thunderhub/src/client/.next/server/chunks/1010.js:14:71234)
    at __webpack_require__ (/home/pulkitsharma/thunderhub/src/client/.next/server/webpack-runtime.js:1:145)
    at 79577 (/home/pulkitsharma/thunderhub/src/client/.next/server/chunks/1010.js:1:426143)
    at __webpack_require__ (/home/pulkitsharma/thunderhub/src/client/.next/server/webpack-runtime.js:1:145)
    at 20175 (/home/pulkitsharma/thunderhub/src/client/.next/server/chunks/1010.js:1:327766)
    at __webpack_require__ (/home/pulkitsharma/thunderhub/src/client/.next/server/webpack-runtime.js:1:145)
    at 83654 (/home/pulkitsharma/thunderhub/src/client/.next/server/chunks/1010.js:1:337077)
    at __webpack_require__ (/home/pulkitsharma/thunderhub/src/client/.next/server/webpack-runtime.js:1:145)
    at 99357 (/home/pulkitsharma/thunderhub/src/client/.next/server/chunks/1010.js:1:357338)

> Build error occurred
Error: Failed to collect page data for /forwards
    at /home/pulkitsharma/thunderhub/node_modules/next/dist/build/utils.js:1171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
