### ISSUE TITLE
Collecting page data  ..ReferenceError during build

### ISSUE THREAD

**Issue by kkoenen** [apotdevin/thunderhub#580]
**Describe the problem/bug**
Build exits with error. After running `npm run build` on v0.13.23:

```
 ✓ Creating an optimized production build    
 ✓ Compiled successfully
   Collecting page data  ..ReferenceError: window is not defined
    at /home/*****/thunderhub/src/client/.next/server/chunks/1010.js:14:70826
    at 75015 (/home/*****/thunderhub/src/client/.next/server/chunks/1010.js:14:71234)
    at __webpack_require__ (/home/*****/thunderhub/src/client/.next/server/webpack-runtime.js:1:145)
    at 79577 (/home/*****/thunderhub/src/client/.next/server/chunks/1010.js:1:426143)
    at __webpack_require__ (/home/*****/thunderhub/src/client/.next/server/webpack-runtime.js:1:145)
    at 20175 (/home/*****/thunderhub/src/client/.next/server/chunks/1010.js:1:327766)
    at __webpack_require__ (/home/*****/thunderhub/src/client/.next/server/webpack-runtime.js:1:145)
    at 83654 (/home/*****/thunderhub/src/client/.next/server/chunks/1010.js:1:337077)
    at __webpack_require__ (/home/*****/thunderhub/src/client/.next/server/webpack-runtime.js:1:145)
    at 99357 (/home/*****/thunderhub/src/client/.next/server/chunks/1010.js:1:357338)

> Build error occurred
Error: Failed to collect page data for /
    at /home/*****/thunderhub/node_modules/next/dist/build/utils.js:1171:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
```

**Your environment**
* Version of ThunderHub: v0.13.23
* Deployment method:  npm install
* Other relevant environment details: npm 10.2.0, nodejs 21.1.0

**To Reproduce**
Follow installation guide.

**Expected behavior**
Clean build, ready to start.

**Actual behavior**
Error during build.

**Comment by kkoenen** [comment]
with

node v16.20.2
npm v8.19.4

it builds and runs (...)
