### ISSUE TITLE
Force logout on UI crash from recently connected channel (incoming_channel_info :  null)

### ISSUE THREAD

**Issue by atomantic** [apotdevin/thunderhub#598]
**Describe the problem/bug**
After a channel connected recently, thunderhub now crashes immediately on load/login with this error:

```
framework-80ea8c0f440c6a32.js:9 TypeError: Cannot read properties of null (reading 'node2_info')
    at cell (947-a32ab3586086676e.js:1:4593)
    at Xh (framework-80ea8c0f440c6a32.js:9:60991)
    at x (framework-80ea8c0f440c6a32.js:9:119446)
    at Vk (framework-80ea8c0f440c6a32.js:9:99131)
    at framework-80ea8c0f440c6a32.js:9:98998
    at Jk (framework-80ea8c0f440c6a32.js:9:99005)
    at Ok (framework-80ea8c0f440c6a32.js:9:95761)
    at Fk (framework-80ea8c0f440c6a32.js:9:96150)
    at jg (framework-80ea8c0f440c6a32.js:9:44900)
    at framework-80ea8c0f440c6a32.js:9:93662
```

**Your environment**
Umbrel

* Version of ThunderHub:
0.13.29

* Deployment method: 
Docker

-------------

pull request incoming

**Comment by atomantic** [comment]
Note, thunderhub stopped crashing once Amboss reported the purchased Magma into `Valid Channel Seen` status, so it looks like this is an issue where the lightning node accepts the channel as open in a smaller number of blocks than amboss.
